service:
  name: sprinter

plugins:  
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1
  timeout: 30
  memorySize: 128
  resourcePolicy:
    - Effect: Allow
      Principal: "*"
      Action: execute-api:Invoke
      Resource:
        - execute-api:/*/*/*
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "lambda:*"
        - "logs:*"
        - "cloudwatch:*"
        - "ssm:*"
      Resource: "*"

custom:
  serverless-offline:    
    port: 4000

functions:
  graphql:
    handler: src/GraphQL.handler
    # layers:
    #   - {Ref: FirebaseAdminLambdaLayer}
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
# layers:
#   firebaseAdmin:
#     path: layer
#     compatibleRuntimes:
#       - nodejs8.10
