service:
  name: users

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1
  timeout: 30
  memorySize: 128
  resourcePolicy:
    - Effect: Allow
      Principal: "*"
      Action: execute-api:Invoke
      Resource:
        - execute-api:/*/*/*
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "lambda:*"
        - "logs:*"
        - "cloudwatch:*"
        - "ssm:*"
      Resource: "*"

custom:
  webpack:
    webpackConfig: "webpack.config.js" # Name of webpack configuration file
    includeModules: false
    packager: "npm"
    excludeFiles: src/**/*.tsx

functions:
  user:
    handler: src/UserHandler.createUser
    layers:
      - {Ref: FirebaseAdminLambdaLayer}
    events:
      - http: post users

layers:
  firebaseAdmin:
    path: layer
    compatibleRuntimes:
      - nodejs8.10
